/* Generated By:JavaCC: Do not edit this line. ParserConstants.java */
package parser;

public interface ParserConstants {

  int EOF = 0;
  int STAR = 5;
  int COMPARE = 6;
  int E = 7;
  int AE = 8;
  int BE = 9;
  int NE = 10;
  int A = 11;
  int B = 12;
  int SELECT = 13;
  int FROM = 14;
  int WHERE = 15;
  int AND = 16;
  int INSERT = 17;
  int INTO = 18;
  int VALUES = 19;
  int CREATE = 20;
  int TABLE = 21;
  int DROP = 22;
  int DELETE = 23;
  int DATATYPE = 24;
  int BOOLEAN = 25;
  int INT = 26;
  int FLOAT = 27;
  int STRING = 28;
  int ID = 29;

  int DEFAULT = 0;

  String[] tokenImage = {
      "<EOF>",
      "\" \"",
      "\"\\r\"",
      "\"\\t\"",
      "\"\\n\"",
      "\"*\"",
      "<COMPARE>",
      "\"=\"",
      "\">=\"",
      "\"<=\"",
      "\"<>\"",
      "\">\"",
      "\"<\"",
      "<SELECT>",
      "<FROM>",
      "<WHERE>",
      "<AND>",
      "<INSERT>",
      "<INTO>",
      "<VALUES>",
      "<CREATE>",
      "<TABLE>",
      "<DROP>",
      "<DELETE>",
      "<DATATYPE>",
      "<BOOLEAN>",
      "<INT>",
      "<FLOAT>",
      "<STRING>",
      "<ID>",
      "\";\"",
      "\".\"",
      "\",\"",
      "\"(\"",
      "\")\"",
  };

}
